version: 1.0.{build}
environment:
  nodejs_version: "9"

branches:
    only:
      - master

skip_tags: true

install:
  - npm install -g tfso/AppVeyor#1.0.104

build_script:
  - patch-version
  - npm run build 

artifacts:
- path: '\'
  name: swagger.api